// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"time"
)

type Comment struct {
	ID        int        `json:"id"`
	Comment   string     `json:"comment"`
	TweetID   int        `json:"tweet_id"`
	UserID    int        `json:"user_id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type Favorite struct {
	ID        int       `json:"id"`
	TweetID   int       `json:"tweet_id"`
	UserID    int       `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Follow struct {
	ID            int        `json:"id"`
	FollowingUser int        `json:"following_user"`
	FollowedUser  int        `json:"followed_user"`
	CreatedAt     time.Time  `json:"created_at"`
	DeletedAt     *time.Time `json:"deleted_at"`
}

type Img struct {
	ID        int        `json:"id"`
	ImgURL    string     `json:"img_url"`
	TweetID   int        `json:"tweet_id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type Token struct {
	Token      string `json:"token"`
	Iat        string `json:"iat"`
	Exp        string `json:"exp"`
	UserUnique string `json:"user_unique"`
}

type Tweet struct {
	ID          int        `json:"id"`
	TweetUnique string     `json:"tweet_unique"`
	Text        string     `json:"text"`
	UserID      int        `json:"user_id"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
}

type TweetData struct {
	Tweet    *Tweet      `json:"Tweet"`
	Imgs     []*Img      `json:"imgs"`
	Favorite []*Favorite `json:"Favorite"`
}

type User struct {
	ID         int        `json:"id"`
	UserUnique string     `json:"user_unique"`
	Password   string     `json:"password"`
	Nickname   string     `json:"nickname"`
	UserImg    *string    `json:"user_img"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
}

type UserInfo struct {
	User   *User        `json:"user"`
	Tweets []*TweetData `json:"tweets"`
}

type NewTweet struct {
	Token string    `json:"token"`
	Text  string    `json:"text"`
	Imgs  []*string `json:"imgs"`
}

type PutFavorite struct {
	TweetID    int    `json:"tweet_id"`
	Token      string `json:"token"`
	IsFavorite bool   `json:"isFavorite"`
}
