CREATE TABLE tweets
(
  id SERIAL NOT NULL PRIMARY KEY,
  tweet_name VARCHAR(255) NOT NULL UNIQUE,
  text VARCHAR(65535) NOT NULL,
  user_id INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT NULL,
  deleted_at TIMESTAMP DEFAULT NULL
);
ALTER TABLE tweets
ADD FOREIGN KEY (user_id) REFERENCES users (id);